import "@/styles/globals.css";
import NavbarPerso from "@/components/NavbarPerso";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="bg-neutral-400">
          <NavbarPerso />
        </div>
        <div>
          {children}
        </div>
      </body>
    </html>
  )
}
